### ISSUE TITLE
react.js appears to be loaded twice

### ISSUE THREAD

**Issue by catmando** [ruby-hyperloop/hyper-react#194] opened 2016-12-01 19:22 UTC
I can't figure out how or why, but its true...

**Comment by zetachang** [comment] 2016-12-05 15:36
The cause of this is that we currently ship `react` & `react-server` in our default setup (using `react-rails`), and each of them has its own copy of ReactDOM. 

This issue will be fixed when #186 is done.

**Comment by zetachang** [comment] 2016-12-18 08:44
This is fixed in master, by requiring `react/react-source-browser` will ensure only one copy of ReactDOM is loaded.

**Closed as completed by zetachang** 2016-12-18 08:44 UTC
Labels: bug
